window.CONFIG = {
    CLIENT_ID: 'YOUR_NAVER_MAP_CLIENT_ID',
    CLIENT_SECRET: 'YOUR_NAVER_MAP_CLIENT_SECRET',
    SUPABASE: {
        URL: 'YOUR_SUPABASE_URL',
        ANON_KEY: 'YOUR_SUPABASE_ANON_KEY'
    },
}; 
